### ISSUE TITLE
Data load failing when there are No Dictionary Columns

### ISSUE THREAD

**Issue by foryou2030** [HuaweiBigData/carbondata#256]
I think there is a issue when read dictionary for No Dictionary columns .
1.create a cube, assign "name" as high cardinality

CREATE CUBE user_cube DIMENSIONS (name string, age integer) MEASURES (grade numeric) OPTIONS(NO_DICTIONARY (name), PARTITIONER[PARTITION_COUNT=1])

2.load data
load data fact from 'D:/hadoop/srcdata/grade.csv' into cube user_cube options(delimiter ",", fileheader 'name,age,grade')

3.load failure, catch exception

16/04/26 14:56:42 ERROR dictionary.ForwardDictionaryCache: [ggin: Graph - Carbon Surrogate Key Generator][partitionID:0] org.carbondata.core.util.CarbonUtilException: Either dictionary or its metadata does not exist for column identifier :: 6343307f-7230-415c-a562-043a5615b37e
16/04/26 14:56:42 ERROR csvbased.CarbonCSVBasedSeqGenStep: [ggin: Graph - Carbon Surrogate Key Generator][partitionID:0] {0}
org.pentaho.di.core.exception.KettleException: 
org.carbondata.core.util.CarbonUtilException: Either dictionary or its metadata does not exist for column identifier :: 6343307f-7230-415c-a562-043a5615b37e
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.FileStoreSurrogateKeyGenForCSV.initDictionaryCacheInfo(FileStoreSurrogateKeyGenForCSV.java:313)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.FileStoreSurrogateKeyGenForCSV.populateCache(FileStoreSurrogateKeyGenForCSV.java:285)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.FileStoreSurrogateKeyGenForCSV.<init>(FileStoreSurrogateKeyGenForCSV.java:141)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenStep.processRow(CarbonCSVBasedSeqGenStep.java:421)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:40)
	at java.lang.Thread.run(Thread.java:722)

@manishgupta88 ,pls check it,
thanks

**Comment by sraghunandan** [comment]
@foryou2030 pls check and close this issue if working
