### ISSUE TITLE
[BUG]Create table with DICTIONARY_INCLUDE Failure

### ISSUE THREAD

**Issue by eason-lyx** [HuaweiBigData/carbondata#406]
Statement:
 cc.sql("create table  t3 (imei string,deviceInformationId string,mac string,productdate timestamp,updatetime timestamp,gamePointId string,contractNumber string) STORED BY 'org.apache.carbondata.format'  TBLPROPERTIES ('DICTIONARY_INCLUDE'='imei,mac')").show

if DICTIONARY_INCLUDE contain more than 2 columns,and contain the timestamp column,then create table failure.

exception:
Exception in thread "main" java.lang.RuntimeException: Duplicate dimensions found with name : updatetime
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.cubemodel.CubeNewProcessor$$anonfun$process$4.apply(cubeSchema.scala:215)
	at org.apache.spark.sql.cubemodel.CubeNewProcessor$$anonfun$process$4.apply(cubeSchema.scala:209)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at org.apache.spark.sql.cubemodel.CubeNewProcessor.process(cubeSchema.scala:209)
	at org.apache.spark.sql.cubemodel.CubeNewProcessor$.apply(cubeSchema.scala:132)
	at org.apache.spark.sql.cubemodel.CreateCube.run(cubeSchema.scala:1617)

**Comment by eason-lyx** [comment]
bug fixed.so close this issue.
