### ISSUE TITLE
Data Load is failing when no measure is used in create cube command

### ISSUE THREAD

**Issue by mohammadshahidkhan** [HuaweiBigData/carbondata#408]
Command: 
1. CREATE CUBE timestamptypecube DIMENSIONS (doj Timestamp, projectjoindate Timestamp, projectenddate Timestamp) OPTIONS (PARTITIONER [PARTITION_COUNT=1])
2. LOAD DATA fact from '"+ dataFile +"' INTO CUBE timestamptypecube PARTITIONDATA(DELIMITER ',', QUOTECHAR '\"') 

Exception:
INFO  16-05 03:22:22,031 - [Executor task launch worker-1][partitionID:0] Graph execution is started C:\Users\ADMINI~1\AppData\Local\Temp\/carbonstore/269957276806047/etl\default\timestamptypecube\0\0\timestamptypecube.ktr
ERROR 16-05 03:22:22,078 - [timestamptypecube: Graph - Carbon Surrogate Key Generator][partitionID:0] 
java.lang.NullPointerException
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenMeta.updateDimensions(CarbonCSVBasedSeqGenMeta.java:1210)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenMeta.initialize(CarbonCSVBasedSeqGenMeta.java:757)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenStep.processRow(CarbonCSVBasedSeqGenStep.java:322)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
	at java.lang.Thread.run(Thread.java:745)
INFO  16-05 03:22:22,084 - [timestamptypecube: Graph - Sort Key: Sort keystimestamptypecube][partitionID:0] Record Processed For table: timestamptypecube
INFO  16-05 03:22:22,084 - [timestamptypecube: Graph - Sort Key: Sort keystimestamptypecube][partitionID:0] Number of Records was Zero
INFO  16-05 03:22:22,084 - [timestamptypecube: Graph - Sort Key: Sort keystimestamptypecube][partitionID:0] Summary: Carbon Sort Key Step: Read: 0: Write: 0
ERROR 16-05 03:22:22,086 - [timestamptypecube: Graph - Carbon Slice Mergertimestamptypecube][partitionID:timestamptypecube] 
org.pentaho.di.core.exception.KettleException: 
org.carbondata.processing.merger.exeception.SliceMergerException: Problem while renaming inprogress folder to actual
Problem while renaming inprogress folder to actual

	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameFolders(CarbonSliceMergerStep.java:168)
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.processRow(CarbonSliceMergerStep.java:118)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.carbondata.processing.merger.exeception.SliceMergerException: Problem while renaming inprogress folder to actual
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameLoadFolderFromInProgressToNormal(CarbonSliceMergerStep.java:232)
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameFolders(CarbonSliceMergerStep.java:161)
	... 3 more
ERROR 16-05 03:22:22,091 - [timestamptypecube: Graph - MDKeyGentimestamptypecube][partitionID:0] Load Folder Not Present for writing measure metadata  : C:\Users\ADMINI~1\AppData\Local\Temp\/carbonstore/269957276806047\default\timestamptypecube\Fact\Part0\Segment_0\0.inprogress
INFO  16-05 03:22:22,281 - [Executor task launch worker-1][partitionID:0] Graph execution is finished.
ERROR 16-05 03:22:22,281 - [Executor task launch worker-1][partitionID:0] Graph Execution had errors
ERROR 16-05 03:22:22,282 - [Executor task launch worker-1][partitionID:0] 
org.carbondata.processing.etl.DataLoadingException: Internal Errors
	at org.carbondata.processing.csvload.DataGraphExecuter.execute(DataGraphExecuter.java:258)
	at org.carbondata.processing.csvload.DataGraphExecuter.executeGraph(DataGraphExecuter.java:172)
	at org.carbondata.integration.spark.load.CarbonLoaderUtil.executeGraph(CarbonLoaderUtil.java:199)
	at org.carbondata.integration.spark.rdd.CarbonDataLoadRDD$$anon$1.<init>(CarbonDataLoadRDD.scala:195)
	at org.carbondata.integration.spark.rdd.CarbonDataLoadRDD.compute(CarbonDataLoadRDD.scala:159)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
INFO  16-05 03:22:22,291 - DataLoad failure

**Comment by chenliang613** [comment]
@mohammadshahidkhan "create cube ... " syntax need to change in future,please check with @gvramana about the latest DDL supports, let us focus on new DDL syntax.

**Comment by mohammadshahidkhan** [comment]
This  issue is there even with new syntax

**Comment by mohammadshahidkhan** [comment]
Fixed PR #466
