### ISSUE TITLE
Uses "if exists" syntax, show the errors msg for drop table.

### ISSUE THREAD

**Issue by chenliang613** [HuaweiBigData/carbondata#430]
In CarbonExample, uses cc.sql("DROP table if exists t3"), generate the below error message. 
Uses cc.sql("DROP table t3"), doesn't generate the below error message.

Need to fix the issue for support "if exists" syntax.

-----------------------------------
ERROR 17-05 15:19:59,882 - TOK_DROPTABLE (of class org.apache.hadoop.hive.ql.parse.ASTNode)
AUDIT 17-05 15:20:00,255 - [AppledeMacBook-Pro.local]Table Not Found: t3
WARN  17-05 15:20:00,256 - Table Not Found: t3
java.lang.RuntimeException: Table Not Found: t3
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.hive.CarbonMetastoreCatalog.lookupRelation2(CarbonMetastoreCatalog.scala:195)
	at org.apache.spark.sql.hive.CarbonMetastoreCatalog.lookupRelation(CarbonMetastoreCatalog.scala:157)
	at org.apache.spark.sql.CarbonContext$$anon$1.org$apache$spark$sql$catalyst$analysis$OverrideCatalog$$super$lookupRelation(CarbonContext.scala:40)
	at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$$anonfun$lookupRelation$3.apply(Catalog.scala:203)
	at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$$anonfun$lookupRelation$3.apply(Catalog.scala:203)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$class.lookupRelation(Catalog.scala:203)
	at org.apache.spark.sql.CarbonContext$$anon$1.lookupRelation(CarbonContext.scala:40)
	at org.apache.spark.sql.SQLContext.table(SQLContext.scala:739)
	at org.apache.spark.sql.SQLContext.table(SQLContext.scala:735)
	at org.apache.spark.sql.hive.execution.DropTable.run(commands.scala:62)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:69)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:933)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:144)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:129)
	at org.carbondata.integration.spark.rdd.CarbonDataFrameRDD.<init>(CarbonDataFrameRDD.scala:23)
	at org.apache.spark.sql.CarbonContext.sql(CarbonContext.scala:60)
	at org.carbondata.examples.CarbonExample$.main(CarbonExample.scala:57)
	at org.carbondata.examples.CarbonExample.main(CarbonExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by chenliang613** [comment]
#442 has solved it , close this issue.
