### ISSUE TITLE
Direct dictionary dataload failure when used with No dictionary columns

### ISSUE THREAD

**Issue by mohammadshahidkhan** [HuaweiBigData/carbondata#479]
1. Direct dictionary dataload failure when used with No dictionary columns
2. Clean up is not happening after the TestTimestampDataTypeDirectDictionary execution

ERROR 24-05 00:07:45,509 - [NO_DICTIONARY_CARBON_6: Graph - Carbon Surrogate Key Generator][partitionID:0] 
java.lang.ArrayIndexOutOfBoundsException: 8
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenMeta.updateDirectDictionaryColumnsInfo(CarbonCSVBasedSeqGenMeta.java:1577)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenMeta.initialize(CarbonCSVBasedSeqGenMeta.java:794)
	at org.carbondata.processing.surrogatekeysgenerator.csvbased.CarbonCSVBasedSeqGenStep.processRow(CarbonCSVBasedSeqGenStep.java:275)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
	at java.lang.Thread.run(Thread.java:745)
INFO  24-05 00:07:45,510 - [NO_DICTIONARY_CARBON_6: Graph - Sort Key: Sort keysNO_DICTIONARY_CARBON_6][partitionID:0] Record Processed For table: NO_DICTIONARY_CARBON_6
INFO  24-05 00:07:45,510 - [NO_DICTIONARY_CARBON_6: Graph - Sort Key: Sort keysNO_DICTIONARY_CARBON_6][partitionID:0] Number of Records was Zero
INFO  24-05 00:07:45,510 - [NO_DICTIONARY_CARBON_6: Graph - Sort Key: Sort keysNO_DICTIONARY_CARBON_6][partitionID:0] Summary: Carbon Sort Key Step: Read: 0: Write: 0
ERROR 24-05 00:07:45,510 - [NO_DICTIONARY_CARBON_6: Graph - Carbon Slice MergerNO_DICTIONARY_CARBON_6][partitionID:6] 
org.pentaho.di.core.exception.KettleException: 
org.carbondata.processing.merger.exeception.SliceMergerException: Problem while renaming inprogress folder to actual
Problem while renaming inprogress folder to actual

	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameFolders(CarbonSliceMergerStep.java:154)
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.processRow(CarbonSliceMergerStep.java:112)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.carbondata.processing.merger.exeception.SliceMergerException: Problem while renaming inprogress folder to actual
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameLoadFolderFromInProgressToNormal(CarbonSliceMergerStep.java:218)
	at org.carbondata.processing.merger.step.CarbonSliceMergerStep.renameFolders(CarbonSliceMergerStep.java:147)
	... 3 more

**Comment by gvramana** [comment]
merged PR #480
