### ISSUE TITLE
Load csv data,the csv's header should be not case sensitive, please check

### ISSUE THREAD

**Issue by chenliang613** [HuaweiBigData/carbondata#493]
For CarbonExample, change /resource/data.csv 's headers to "ID,Date,Country,Name,Phonetype,Serialname,Salary", then generate the below errors:
－－
ERROR 25-05 11:38:59,099 - [Executor task launch worker-1][partitionID:default_t3_59d74409-5eb0-4b10-8007-47bb384b1d99] Header Columns are not present in the provided CSV File :data.csv
ERROR 25-05 11:38:59,099 - [Executor task launch worker-1][partitionID:default_t3_59d74409-5eb0-4b10-8007-47bb384b1d99] 
org.carbondata.processing.etl.DataLoadingException: Header Columns are not present in the provided CSV File:data.csv
	at org.carbondata.processing.csvload.DataGraphExecuter.validateCSV(DataGraphExecuter.java:156)
	at org.carbondata.processing.csvload.DataGraphExecuter.validateCSVFiles(DataGraphExecuter.java:544)
	at org.carbondata.processing.csvload.DataGraphExecuter.executeGraph(DataGraphExecuter.java:166)
	at org.carbondata.spark.load.CarbonLoaderUtil.executeGraph(CarbonLoaderUtil.java:180)
	at org.carbondata.spark.rdd.CarbonDataLoadRDD$$anon$1.<init>(CarbonDataLoadRDD.scala:183)
	at org.carbondata.spark.rdd.CarbonDataLoadRDD.compute(CarbonDataLoadRDD.scala:147)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
AUDIT 25-05 11:38:59,108 - [AppledeMacBook-Pro.local]The data loading is failed.
WARN  25-05 11:38:59,109 - Unable to write load metadata file
ERROR 25-05 11:38:59,109 - main 
java.lang.Exception: Dataload failure
	at org.carbondata.spark.rdd.CarbonDataRDDFactory$.loadCarbonData(CarbonDataRDDFactory.scala:451)
	at org.apache.spark.sql.execution.command.LoadCube.run(carbonTableSchema.scala:1414)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:69)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:933)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:144)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:129)
	at org.carbondata.spark.rdd.CarbonDataFrameRDD.<init>(CarbonDataFrameRDD.scala:23)
	at org.apache.spark.sql.CarbonContext.sql(CarbonContext.scala:63)
	at org.carbondata.examples.CarbonExample$.main(CarbonExample.scala:66)
	at org.carbondata.examples.CarbonExample.main(CarbonExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
AUDIT 25-05 11:38:59,109 - [AppledeMacBook-Pro.local]Dataload failure. Please check the logs
Exception in thread "main" java.lang.RuntimeException: Dataload failure. Please check the logs
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.execution.command.LoadCube.run(carbonTableSchema.scala:1422)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:69)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:933)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:144)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:129)
	at org.carbondata.spark.rdd.CarbonDataFrameRDD.<init>(CarbonDataFrameRDD.scala:23)
	at org.apache.spark.sql.CarbonContext.sql(CarbonContext.scala:63)
	at org.carbondata.examples.CarbonExample$.main(CarbonExample.scala:66)
	at org.carbondata.examples.CarbonExample.main(CarbonExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

**Comment by chenliang613** [comment]
This issue will be fixed in #485

**Comment by chenliang613** [comment]
The latest version is ok for this issue, close it.
