### ISSUE TITLE
[Bug]path error for windows system during dataloading

### ISSUE THREAD

**Issue by QiangCai** [HuaweiBigData/carbondata#576]
Reproduce:
run testcase on windows system

Exception:
java.lang.IllegalArgumentException: Illegal escaped string c:\fd.csv unescaped \ at 2
	at org.apache.hadoop.util.StringUtils.unEscapeString(StringUtils.java:552)
	at org.apache.hadoop.util.StringUtils.unEscapeString(StringUtils.java:534)
	at org.apache.hadoop.util.StringUtils.unEscapeString(StringUtils.java:520)
	at org.carbondata.examples.TestPath$.main(TestPath.scala:9)
	at org.carbondata.examples.TestPath.main(TestPath.scala)

**Comment by QiangCai** [comment]
fixed
