### ISSUE TITLE
Quick-Start Failed: Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database /usr/local/Cellar/apache-spark/1.6.1/libexec/metastore_db.

### ISSUE THREAD

**Issue by EasonYi** [HuaweiBigData/carbondata#582]
### 1. Started Spark-Shell Sucessfully
```
INFO  06-06 14:06:43,855 - Created local directory: /var/folders/pd/hnjlg_y92518jzjr85fkv7q80000gn/T/eason/33c4549a-70f7-445a-83ea-a08388bfb899
INFO  06-06 14:06:43,860 - Created HDFS directory: /tmp/hive/eason/33c4549a-70f7-445a-83ea-a08388bfb899/_tmp_space.db
INFO  06-06 14:06:43,869 - Created sql context (with Hive support)..
SQL context available as sqlContext.
```
### 2. Imported Classes Successfully
```
import org.apache.spark.sql.CarbonContext
import java.io.File
import org.apache.hadoop.hive.conf.HiveConf
```
### 3. Failed to Create CarbonContext
```
val cc = new CarbonContext(sc, "./carbondata/store")

	... 125 more
Caused by: java.sql.SQLException: Another instance of Derby may have already booted the database /usr/local/Cellar/apache-spark/1.6.1/libexec/metastore_db.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	... 122 more
Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database /usr/local/Cellar/apache-spark/1.6.1/libexec/metastore_db.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)
	at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)
```
### How to Resolve it?
**Spark-shell created HiveContext automatically:**
```
scala> sqlContext
res0: org.apache.spark.sql.SQLContext = org.apache.spark.sql.hive.HiveContext@1828eff
```

**Comment by chenliang613** [comment]
1.please use spark 1.5
2.Hive's Derby.db only support one connection, so please refer to the below method to set:
http://www.cloudera.com/documentation/archive/cdh/4-x/4-2-0/CDH4-Installation-Guide/cdh4ig_topic_18_4.html
