### ISSUE TITLE
UT failed in CarbonTestSuite with native code

### ISSUE THREAD

**Issue by Hexiaoqiao** [HuaweiBigData/carbondata#648]
when i run UT in my localhost, it failed since 2 exceptions throws in {DataCompactionCardinalityBoundryTest} and {DataCompactionNoDictionaryTest}.

my local env:
OS:Darwin Kernel Version 15.5.0,RELEASE_X86_64
JDK:jdk1.7.0_75
Scala:2.11.5

exception trace:
> DataCompactionNoDictionaryTest:
Exception encountered when invoking run on a nested suite - alter table failed. table not found: default_noDictionaryCompaction *** ABORTED ***
  java.lang.RuntimeException: alter table failed. table not found: default_noDictionaryCompaction
  at scala.sys.package$.error(package.scala:27)
  at org.apache.spark.sql.execution.command.AlterTableCompaction.run(carbonTableSchema.scala:1162)
  at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57)
  at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57)
  at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:69)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:140)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
  at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)
  ...

> DataCompactionCardinalityBoundryTest:
Exception encountered when invoking run on a nested suite - alter table failed. table not found: default_cardinalityTest *** ABORTED ***
  java.lang.RuntimeException: alter table failed. table not found: default_cardinalityTest
  at scala.sys.package$.error(package.scala:27)
  at org.apache.spark.sql.execution.command.AlterTableCompaction.run(carbonTableSchema.scala:1162)
  at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57)
  at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57)
  at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:69)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:140)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
  at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)

**Comment by ravipesala** [comment]
@Hexiaoqiao Can you take latest code and run again. It seems this bug is fixed recently.

**Comment by Hexiaoqiao** [comment]
@ravipesala thanks for your comment. it looks not resolve completely. my local code is same as branch master, and abort when run ut. see the following commit log is latest code:
> hexiaoqiaodeMacBook-Pro:carbondata hexiaoqiao$ git log --oneline | head -1
> efc41b2 [Issue-587] carbon table name should be case insensitive (#590)

**Comment by Hexiaoqiao** [comment]
@ravipesala this may be a common problem since it abort by the same type exception when i run ut in multiple platform using the latest code. FYI.

**Comment by ravipesala** [comment]
@Hexiaoqiao . Thank you for pointing out.
Yes, It is an issue and supposed to be fixed by PR https://github.com/HuaweiBigData/carbondata/pull/590 . But it did not fix completely. Already one contributor is working on it and expecting it will be resolved soon.

**Comment by Hexiaoqiao** [comment]
@ravipesala  OK, thanks, I will close this ticket when #662 finish.
