### ISSUE TITLE
select count(joinDate) from table_x is failing direct dictionary column

### ISSUE THREAD

**Issue by mohammadshahidkhan** [HuaweiBigData/carbondata#664]
select count(joinDate) from table_x is failing direct dictionary column

**Comment by mohammadshahidkhan** [comment]
org.carbondata.query.carbon.executor.exception.QueryExecutionException: 
	at org.carbondata.query.carbon.processor.impl.AggregateQueryBlockProcessor.processBlock(AggregateQueryBlockProcessor.java:57)
	at org.carbondata.query.carbon.executor.internal.impl.QueryRunner.call(QueryRunner.java:72)
	at org.carbondata.query.carbon.executor.internal.impl.QueryRunner.call(QueryRunner.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.carbondata.query.carbon.aggregator.dimension.impl.FixedLengthDimensionAggregator.aggregateDimensionData(FixedLengthDimensionAggregator.java:102)
	at org.carbondata.query.carbon.aggregator.DataAggregator.aggregateData(DataAggregator.java:71)
	at org.carbondata.query.carbon.aggregator.impl.MapBasedResultAggregator.aggregateData(MapBasedResultAggregator.java:109)
	at org.carbondata.query.carbon.processor.impl.AggregateQueryBlockProcessor.processBlock(AggregateQueryBlockProcessor.java:55)
	... 6 more

**Comment by mohammadshahidkhan** [comment]
Fixed with PR #665
