### ISSUE TITLE
[Bug]use POINT in tableUniqueName intead of UNDERSCORE

### ISSUE THREAD

**Issue by QiangCai** [HuaweiBigData/carbondata#723]
**Reproduce:**
In CarbonExample, when I create two table: u_u.u and u.u_u,  I find that these tables have same unique name "u_u_u".
Codes as following.

``` scala
    cc.sql("create database u_u")
    cc.sql("create database u")

    cc.sql("""
           CREATE TABLE IF NOT EXISTS u_u.u
           (ID Int, date Timestamp, country String,
           name String, phonetype String, serialname String, salary Int)
           STORED BY 'org.apache.carbondata.format'
           """)

    cc.sql("""
           CREATE TABLE IF NOT EXISTS u.u_u
           (ID Int, date Timestamp, country String,
           name String, phonetype String, serialname String, salary Int)
           STORED BY 'org.apache.carbondata.format'
           """)


    cc.sql(s"""
           LOAD DATA LOCAL INPATH '$testData' into table u_u.u
           """)

    cc.sql("""
           SELECT country, count(salary) AS amount
           FROM u_u.u
           WHERE country IN ('china','france')
           GROUP BY country
           """).show()

    cc.sql("""
           SELECT country, count(salary) AS amount
           FROM u.u_u
           WHERE country IN ('china','france')
           GROUP BY country
           """).show()
```

**Exception:**
ERROR 23-06 14:50:18,560 - [u: Graph - MDKeyGenu][partitionID:0] Problem while copying file from local store to carbon store
org.carbondata.processing.store.writer.exception.CarbonDataWriterException: Problem while copying file from local store to carbon store
    at org.carbondata.processing.store.writer.AbstractFactDataWriter.copyCarbonDataFileToCarbonStorePath(AbstractFactDataWriter.java:484)
    at org.carbondata.processing.store.writer.AbstractFactDataWriter.closeWriter(AbstractFactDataWriter.java:424)
    at org.carbondata.processing.store.CarbonFactDataHandlerColumnar.closeHandler(CarbonFactDataHandlerColumnar.java:872)
    at org.carbondata.processing.mdkeygen.MDKeyGenStep.processingComplete(MDKeyGenStep.java:223)
    at org.carbondata.processing.mdkeygen.MDKeyGenStep.processRow(MDKeyGenStep.java:216)
    at org.pentaho.di.trans.step.RunThread.run(RunThread.java:50)
    at java.lang.Thread.run(Thread.java:745)

**Solution:**
change to use POINT in tableUniqueName intead of UNDERSCORE

**Comment by QiangCai** [comment]
I will raise pr to fix it.

**Comment by QiangCai** [comment]
[PR-724](https://github.com/HuaweiBigData/carbondata/pull/724)
