### ISSUE TITLE
Failed to generate global dictionary files

### ISSUE THREAD

**Issue by ustczen** [HuaweiBigData/carbondata#855]
Hi, guys
Recently I try to set up an adhoc query engine with CarbonData following this link:http://www.jianshu.com/p/99e4893065d7.
I try to convert csv file into Carbon file, unfortunately the spark cluster throw an exception when I use 3000 million rows of csv: 
> Failed to generate global dictionary files

However, when I reduce my data file to 300 million rows, everything is OK. Below is my command, any ideas?
```shell
./bin/spark-shell --master yarn-client --jars ./carbondata/*.jar ./lib/datanucleus*.jar  --num-executors 27 --executor-cores 12 --executor-memory 30G
```

**Comment by ustczen** [comment]
some related logs may help, I've replace the columns' name with xxxxx
```scala
INFO  22-07 23:45:03,789 - Finished task 5.1 in stage 2.0 (TID 849) in 92511 ms on sparkcluster-30-10.gtj (52/53)
INFO  22-07 23:47:40,082 - Finished task 13.1 in stage 2.0 (TID 848) in 250538 ms on sparkcluster-30-10.gtj (53/53)
INFO  22-07 23:47:40,082 - ResultStage 2 (collect at GlobalDictionaryUtil.scala:483) finished in 951.679 s
INFO  22-07 23:47:40,082 - Removed TaskSet 2.0, whose tasks have all completed, from pool 
INFO  22-07 23:47:40,083 - Job 1 finished: collect at GlobalDictionaryUtil.scala:483, took 1146.830091 s
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,087 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - table:carbondata_large_test column:xxxxx generate global dictionary file failed
ERROR 22-07 23:47:40,088 - generate global dictionary files failed
ERROR 22-07 23:47:40,089 - generate global dictionary failed
ERROR 22-07 23:47:40,089 - main 
java.lang.Exception: Failed to generate global dictionary files
        at org.carbondata.spark.util.GlobalDictionaryUtil$.org$carbondata$spark$util$GlobalDictionaryUtil$$checkStatus(GlobalDictionaryUtil.scala:441)
        at org.carbondata.spark.util.GlobalDictionaryUtil$.generateGlobalDictionary(GlobalDictionaryUtil.scala:485)
        at org.apache.spark.sql.execution.command.LoadTable.run(carbonTableSchema.scala:1144)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
        at org.carbondata.spark.rdd.CarbonDataFrameRDD.<init>(CarbonDataFrameRDD.scala:23)
        at org.apache.spark.sql.CarbonContext.sql(CarbonContext.scala:109)
        at $line27.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:35)
        at $line27.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
        at $line27.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:42)
        at $line27.$read$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:44)
        at $line27.$read$$iwC$$iwC$$iwC$$iwC.<init>(<console>:46)
        at $line27.$read$$iwC$$iwC$$iwC.<init>(<console>:48)
        at $line27.$read$$iwC$$iwC.<init>(<console>:50)
        at $line27.$read$$iwC.<init>(<console>:52)
        at $line27.$read.<init>(<console>:54)
        at $line27.$read$.<init>(<console>:58)
        at $line27.$read$.<clinit>(<console>)
        at $line27.$eval$.<init>(<console>:7)
        at $line27.$eval$.<clinit>(<console>)
        at $line27.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
        at org.apache.spark.repl.Main$.main(Main.scala:31)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
AUDIT 22-07 23:47:40,092 - [sparkcluster-30-1.gtj][root][Thread-1]Dataload failure for default.carbondata_large_test. Please check the logs
INFO  22-07 23:47:40,098 - Table MetaData Unlocked Successfully after data load
java.lang.Exception: Failed to generate global dictionary files
        at org.carbondata.spark.util.GlobalDictionaryUtil$.org$carbondata$spark$util$GlobalDictionaryUtil$$checkStatus(GlobalDictionaryUtil.scala:441)
        at org.carbondata.spark.util.GlobalDictionaryUtil$.generateGlobalDictionary(GlobalDictionaryUtil.scala:485)
        at org.apache.spark.sql.execution.command.LoadTable.run(carbonTableSchema.scala:1144)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
        at org.carbondata.spark.rdd.CarbonDataFrameRDD.<init>(CarbonDataFrameRDD.scala:23)
        at org.apache.spark.sql.CarbonContext.sql(CarbonContext.scala:109)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:35)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:42)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:44)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:46)
        at $iwC$$iwC$$iwC.<init>(<console>:48)
        at $iwC$$iwC.<init>(<console>:50)
        at $iwC.<init>(<console>:52)
        at <init>(<console>:54)
        at .<init>(<console>:58)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
        at org.apache.spark.repl.Main$.main(Main.scala:31)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by sujith71955** [comment]
Hi, What i can observe is you have to process around 300 million data since you have not provided driver memory in your command parameter, the default diver memory memory will be taken from spark-default.conf file,please refer the file to know how much default driver memory is been assigned,if its too less please increase the memory as mentioned below
1) provide driver memory in the command line like below
./bin/spark-shell --master yarn-client --jars ./carbondata/*.jar ./lib/datanucleus*.jar  --num-executors 27 --executor-cores 12 --executor-memory 30G --driver-memory 20G

2) Also one more suggestion is based on node manager you can determine number of executors.

**Comment by ustczen** [comment]
Hi @sujith71955 , many thanks for your reply.
Actually I've set driver-memory at conf/spark-env.sh : 
> export SPARK_DRIVER_MEMORY=30G

Be prudent, I use the command below, but the problem is still there..:

```shell
./bin/spark-shell --master yarn-client --jars ./carbondata/*.jar  --num-executors 25 --executor-cores 12 --executor-memory 30G  --driver-memory 50G
```

**Comment by chenliang613** [comment]
Please go to Apache JIRA for discussing this issue : https://issues.apache.org/jira/browse/CARBONDATA-98
